remote_theme: pages-themes/modernist@v0.2.0
plugins:
- jekyll-remote-theme
title: jd
description: produce and apply JSON structural diffs
show_downloads: true
github:
  release_url: https://github.com/josephburnett/jd/releases/latest
